### ISSUE TITLE
Access Token?

### ISSUE THREAD

**Issue by donavanbecker** [h3l1o5/pyyardian#1]
How do you access the Access Token in the Yardian App?

**Comment by h3l1o5** [comment]
Hi @donavanbecker 

We'll release an in-app update for Yardian App tomorrow to support the access token functionality.

**Comment by donavanbecker** [comment]
Thanks @h3l1o5!

**Comment by h3l1o5** [comment]
The new Yardian App version is released! Please update your app to v4.8.2 through in-app update and make sure your device's firmware version is 6.18.0 or higher as well. 😃

**Comment by donavanbecker** [comment]
I was able to set up the integration! Thanks!
